### ISSUE TITLE
Unexpected signature for firebase phone

### ISSUE THREAD

**Issue by serhanbuy** [ConnectyCube/connectycube-server-api#2]
Hello,
this was working fine before but now we are receiving an "Unexpected signature" error while trying to authenticate. 

Below is the relevant portion of our code. Is there something we are missing with the order or something else?

```
$signature_string = application_id=".APPLICATION_ID."&auth_key=".AUTH_KEY."&firebase_phone[access_token]=".$fbtoken."&firebase_phone[project_id]=".$fb_project_id."&nonce=".$nonce."&provider=".'firebase_phone'."&timestamp=".$timestamp;

$signature = hash_hmac('sha1', $signature_string , AUTH_SECRET);

// Build post body
$post_body = http_build_query(array(
                'application_id' => APPLICATION_ID,
                'auth_key' => AUTH_KEY,
                'timestamp' => $timestamp,
                'nonce' => $nonce,
                'signature' => $signature,
                'provider' => 'firebase_phone',
                'firebase_phone[project_id]' => $fb_project_id,
                'firebase_phone[access_token]' => $fbtoken
                ));
```

**Comment by DaveLomber** [comment]
do you provide any headers when make a request?

**Comment by serhanbuy** [comment]
@DaveLomber  thank you for the response.

No actually there is no header.


```
$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, CB_API_ENDPOINT . '/' . CB_PATH_SESSION); // Full path is - https://api.connectycube.com/session.json
curl_setopt($curl, CURLOPT_POST, true); // Use POST
curl_setopt($curl, CURLOPT_POSTFIELDS, $post_body); // Setup post body
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true); // Receive server response

// Execute request and read responce
$responce = curl_exec($curl);

```


PS: the signature check returns OK if we remove the firebase related stuff

**Comment by banshiAnton** [comment]
Hi @serhanbuy, can you please provide full string $signature_string
value

**Comment by serhanbuy** [comment]
@banshiAnton 

I am obscuring some of the original string with **** for safety reasons.

`application_id=12**&auth_key=C4A*******&firebase_phone[access_token]=eyJhbGciOiJ***************k5Zjg3MGYyOGUyOTg5YWI0ODFjYzJlNDdlMGUyY2MxOWQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY3lvdS1iZDVlMyIsImF1ZCI6ImN5b3UtYmQ1ZTMiLCJhdXRoX3RpbWUiOjE2MjMxNTQ0OTYsInVzZXJfaWQiOiJCb0VrbHVaOEQ3UE45cHJIbmJuRHhZRldkeGQyIiwic3ViIjoiQm9Fa2x1WjhEN1BOOXBySG5ibkR4WUZXZHhkMiIsImlhdCI6MTYyMzE1NDQ5NiwiZXhwIjoxNjIzMTU4MDk2LCJwaG9uZV9udW1iZXIiOiIrOTE3OTkwMjI5NDM0IiwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJwaG9uZSI6WyIrOTE3OTkwMjI5NDM0Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGhvbmUifX0.ehpk9FtQAThLcnB349GdIJxg0RN2YLXGiv3iRxSDD7IEgyMsreeKJtrp7TG9eYeVu4Lms6g5hbPlBNMCIPZijdsGfVy-uRxlJLefo0J33a3Ek2tKpDFg9Dvl-SObZ_u8_buPjA_y1QNmWXa7zJErzgaNWZvuqmSEIodgEIGUwBzDLOoNUY0VwgU_MoylRUiXV2z_CIzNWcra7027lVomDsuBqUnABNCrUeA4xYdP7Luta1PzJEBW_Q6wVeGddW95mOPHdJsBb_nLE8VlC-uAxA9053gkyVBqakFEkeSZgwSS8XhpJCVs16IDzpUb4YyC1r6X4659kmWgHI7QblKvrg&firebase_phone[project_id]=cyou-bd5e3&nonce=203004056&provider=firebase_phone&timestamp=1623752788`


signature is

`33489f36c5023eabd6d94619f9f3b70d07b2cb77`

**Comment by DaveLomber** [comment]
@serhanbuy can you check again and let us know

**Comment by serhanbuy** [comment]
Hello, thank you for the support. It is back to normal and no error is thrown 👍
